### ISSUE TITLE
Reduce gas cost of deploying a Graph Curation Token by using MinimalProxy

### ISSUE THREAD

**Issue by abarmat** [graphprotocol/contracts#405]
The gas cost of deploying the subgraph token can be greatly optimized by deploying a minimal proxy each time, sharing the same bytecode.

**Comment by tmigone** [comment]
@abarmat I think we can close this as it was implemented in https://github.com/graphprotocol/contracts/pull/505 right? Or are there further optimizations you think can be made?

**Comment by abarmat** [comment]
@tmigone exactly this is already implemented, I'll close it
