### ISSUE TITLE
Link to https://github.com/graphprotocol/graph-network-subgraph inaccessible

### ISSUE THREAD

**Issue by gpersoon** [graphprotocol/contracts#444]
The readme of https://github.com/graphprotocol/contracts:
https://github.com/graphprotocol/contracts/blob/master/README.md

Contains a link to https://github.com/graphprotocol/graph-network-subgraph,
In the text: "The subgraph repository can be [found here](https://github.com/graphprotocol/graph-network-subgraph)."
However this link is not accessible.

See Line 47: 
```JS
The subgraph repository can be [found here](https://github.com/graphprotocol/graph-network-subgraph).
```

**Comment by tmigone** [comment]
Most likely the repo was set to private back in 2020. Two years later it is public and accesible to anyone. Also the subgraph mentions on the README were removed in https://github.com/graphprotocol/contracts/pull/500
