### ISSUE TITLE
TypeError: Cannot read property 'connect' of undefined

### ISSUE THREAD

**Issue by ru-errorist** [graphprotocol/contracts#449]
Hello team. While following [the instructions](https://github.com/graphprotocol/indexer/blob/main/docs/networks.md#testnet-httpstestnetthegraphcom-rinkeby) for testnet staking, I receive tracebacks while sending a transaction. I've done the following steps:
1. Signed up in Infura and created a project
2. Installed Ubuntu 20.04.2 LTS with apt update and upgrade executed
2. Installed git and npm
3. Run `./cli/cli.ts -m 'one two ... twelve' -p https://rinkeby.infura.io/v3/29c...b38 \
  contracts graphToken approve --account 0x2d44C0e097F6cD0f514edAC633d82E01280B4A5c --amount 1000000`
4. Received `/usr/bin/env: ‘ts-node’: No such file or directory`
5. Run `npm install -g ts-node`
6. Run command from point 3 once again and received the following output: [graph-testnet.txt](https://github.com/graphprotocol/contracts/files/5976098/graph-testnet.txt). Amongst others there're tracebacks in the end of an output:
`TypeError: Cannot read property 'connect' of undefined
    at Object.exports.sendTransaction (/root/contracts/cli/network.ts:120:50)
    at Object.exports.approve (/root/contracts/cli/commands/contracts/graphToken.ts:42:9)
    at Object.handler (/root/contracts/cli/commands/contracts/graphToken.ts:138:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)`
7. Run 'stacking' command with same errors in an output

I've checked that Infura is still being used with the following methods being called:
1. eth_chainId (4 times)
2. eth_getBalance
3. eth_getTransactionCount

The versions are the following:
node --version
v10.19.0
./cli/cli.ts --version
1.1.0

**Comment by Krewedk0** [comment]
Had similar issue, you have to compile contracts first
`npm run compile`

**Comment by davekaj** [comment]
Thanks @Krewedk0 . Does this solve your problem @ru-errorist  ?

**Comment by diman-io** [comment]
I had the same problem and this helped

**Comment by begetan** [comment]
@Jannis Could you update the testnet readme?

**Comment by lenox11** [comment]
Thanks @Krewedk0!

**Comment by ru-errorist** [comment]
@Krewedk0 Thanks a lot!
@davekaj Yes it worked for me.
