### ISSUE TITLE
Stale comment for _getSlashingPercentageForDisputeType in DisputeManager

### ISSUE THREAD

**Issue by yondonfu** [graphprotocol/contracts#478]
This [comment](https://github.com/graphprotocol/contracts/blob/dd7113abdd6a4d0ef98788d0177a98cd450a5166/contracts/disputes/DisputeManager.sol#L701) for `_getSlashingPercentageForDisputeType` in the `DisputeManager` contract says "Recover the signer address of the _attestation". Looks like it is an old comment that just needs to be updated.

**Comment by abarmat** [comment]
@yondonfu that's a good catch, I'll update the comment, thank you

**Comment by abarmat** [comment]
Fixed in https://github.com/graphprotocol/contracts/commit/7f811fb5e967a1b4273a8193c4280226dc02c5b6
