### ISSUE TITLE
Deploy contracts to Sepolia and/or Goerli

### ISSUE THREAD

**Issue by willianpaixao** [graphprotocol/contracts#587]
The Ethereum Foundation [announced](https://blog.ethereum.org/2022/06/21/testnet-deprecation/) the deprecation of the Rinkeby network.

The contracts need to be deployed to Sepolia (at least) as the new de facto testnet and the address book updated.

**Comment by trader-payne** [comment]
Hi. We are aware of the deprecation of those chains, and we're planning to move the testnet to Goerli.

**Comment by tmigone** [comment]
Hi, just to confirm, we are working on deploying the protocol to Goerli in the next couple days.

**Comment by willianpaixao** [comment]
Thank you!
