### ISSUE TITLE
Add initialization actions to protocol deployment script

### ISSUE THREAD

**Issue by tmigone** [graphprotocol/contracts#629]
The following actions need to be performed manually when deploying the protocol:

- Deployer renounce minter (GraphToken.renounceMinter)
- Set subgraph availability oracle (RewardsManager.setSubgraphAvailabilityOracle)
- Set AssetHolder (Staking.setAssetHolder)
- Set Pause Guardian (Controller.setPauseGuardian)
- Transfer contract ownership to governor
   - Controller
   - GraphProxyAdmin
   - GraphToken
   - SubgraphNFT
- Transfer contract ownership to allocation exchange owner
   - AllocationExchange

These could be done automatically by incorporating the required parameters into the config file `graph.<network>.yml`

**Comment by Goldmindsx** [comment]
> The following actions need to be performed manually when deploying the protocol:
> 
> * Deployer renounce minter (GraphToken.renounceMinter)
> * Set subgraph availability oracle (RewardsManager.setSubgraphAvailabilityOracle)
> * Set AssetHolder (Staking.setAssetHolder)
> * Set Pause Guardian (Controller.setPauseGuardian)
> * Transfer contract ownership to governor
>   
>   * Controller
>   * GraphProxyAdmin
>   * GraphToken
>   * SubgraphNFT
> * Transfer contract ownership to allocation exchange owner
>   
>   * AllocationExchange
> 
> These could be done automatically by incorporating the required parameters into the config file `graph.<network>.yml`

talk to graph protocol via live chat https://direct.lc.chat/14345826/

**Comment by tmigone** [comment]
Fixed in #631
